spring:
  application:
    name: CircuitsCourtsAPI
  datasource:
      url: jdbc:mysql://localhost:3306/ecocircuits?useSSL=false&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: error
    com.lifat: info
    org.springframework.boot.web.embedded.tomcat: info
    org.hibernate.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 9020

mvc:
  cross-origins:
    allowed-origins:
      - http://localhost:9020
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE

com:
    lifat:
        circuits_courts:
        jwt:
            secret: mySecretKey
            expiration: 86400000
